// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmOrganizer.Models
{
    public partial class CropField
    {
        public CropField()
        {
            BalanceLedger = new HashSet<BalanceLedger>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public double Hectares { get; set; }

        public virtual ICollection<BalanceLedger> BalanceLedger { get; set; }

        public override string ToString()
        {
            return $"{Name} ({Hectares} ha)";
        }
    }
}